---
- name: Configure Nginx on EC2
  hosts: webservers
  become: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install NGINX
      apt:
        name: nginx
        state: present
      notify: Restart Nginx

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Replace default index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head><title>Deployed by Ansible</title></head>
          <body><h1>Hello from Ansible Automation!</h1></body>
          </html>

    - name: Copy test.php to Nginx web root
      copy:
        src: test.php
        dest: /var/www/html/test.php
        mode: '0644'

    - name: Harden SSH configuration
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Restart SSH
      service:
        name: ssh
        state: restarted
