---
- name: Configure Nginx on EC2
  hosts: webservers
  become: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install NGINX and PHP-FPM
      apt:
        name: 
          - nginx
          - php-fpm
          - php-mysql
        state: present
      notify: 
        - Restart Nginx
        - Restart PHP-FPM

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Start and enable PHP-FPM
      service:
        name: php8.1-fpm  # Adjust version as needed
        state: started
        enabled: yes

    - name: Configure Nginx default site for PHP
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80 default_server;
              listen [::]:80 default_server;

              root /var/www/html;
              index index.php index.html index.htm index.nginx-debian.html;

              server_name _;

              location / {
                  try_files $uri $uri/ =404;
              }

              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
              }

              location ~ /\.ht {
                  deny all;
              }
          }
      notify: Restart Nginx

    - name: Test Nginx configuration
      command: nginx -t
      changed_when: false

    - name: Replace default index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head><title>Deployed by Ansible</title></head>
          <body><h1>Hello from Ansible Automation!</h1></body>
          </html>

    - name: Copy test.php to Nginx web root
      copy:
        src: test.php
        dest: /var/www/html/test.php
        mode: '0644'
        owner: www-data
        group: www-data

    - name: Harden SSH configuration
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Restart PHP-FPM
      service:
        name: php8.1-fpm
        state: restarted

    - name: Restart SSH
      service:
        name: ssh
        state: restarted