- name: Configure Web Server
  hosts: web
  become: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install NGINX
      apt:
        name: nginx
        state: present
      notify: Restart Nginx

    - name: Deploy a test webpage
      copy:
        content: "<h1>Hello from Shawn's Automated Cloud Server!</h1>"
        dest: /var/www/html/index.html

    - name: Harden SSH configuration
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
    - name: Restart SSH
      service:
        name: sshd
        state: restarted