---
- name: Configure Nginx and PHP-FPM on EC2
  hosts: webservers
  become: yes

  vars:
    php_fpm_sock: "/run/php/php-fpm.sock"
    # If your system uses a versioned socket (like php8.1-fpm.sock), auto-detect with a shell command or adjust this variable.

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install NGINX and PHP-FPM
      apt:
        name:
          - nginx
          - php-fpm
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Start and enable PHP-FPM
      service:
        name: "{{ lookup('ansible.builtin.service_facts').services | dict2items | selectattr('key','match','php.*-fpm') | map(attribute='key') | list | first | default('php8.1-fpm') }}"
        state: started
        enabled: yes

    - name: Copy test.php to Nginx web root
      copy:
        src: ansible/test.php
        dest: /var/www/html/test.php
        mode: '0644'

    - name: Replace default index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head><title>Deployed by Ansible</title></head>
          <body><h1>Hello from Ansible Automation!</h1></body>
          </html>

    - name: Ensure index.php is in the index line
      lineinfile:
        path: /etc/nginx/sites-available/default
        regexp: '^(\s*)index\s+'
        line: '        index index.php index.html index.htm index.nginx-debian.html;'
        backrefs: yes

    - name: Ensure PHP location block exists
      blockinfile:
        path: /etc/nginx/sites-available/default
        marker: "# {mark} ANSIBLE MANAGED PHP BLOCK"
        insertafter: '^(\s*)index.+;$'
        block: |
          location ~ \.php$ {
              include snippets/fastcgi-php.conf;
              fastcgi_pass unix:{{ php_fpm_sock }};
          }

    - name: Reload Nginx to apply config changes
      service:
        name: nginx
        state: reloaded

    - name: Harden SSH configuration
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted