name: Deploy Web Server

on:
  push:
    branches:
      - main
    paths:
      - '**.yml'
      - '**.sh'
      - '**.php'
      - '**.tf'
      - '**.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > shawn-key.pem
          chmod 600 shawn-key.pem

      - name: Run setup script on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i shawn-key.pem ubuntu@54.82.93.197 '
            sudo bash -s' < setup.sh

      - name: Confirm deployment finished
        run: echo "✅ EC2 instance successfully configured via Ansible & setup.sh"
